# Numpy


### 1. Please import Numpy


In [1]:
import numpy as np

### 2. Create an array of 10 zeros


In [4]:
zeros_array = np.zeros(10)
zeros_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### 3. Create an array of even numbers between 12 and 52


In [5]:
even_numbers = np.arange(12, 53, 2)
even_numbers

array([12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44,
       46, 48, 50, 52])

### 4. Create a 3x3 matrix with values from 5 to 13


In [6]:
matrix_3x3 = np.arange(5, 14).reshape(3, 3)
matrix_3x3

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

### 5. Create a 3x3 diagonal matrix with values 4, 8, and 12 on the diagonal


In [7]:
diagonal_matrix = np.diag([4, 8, 12])
diagonal_matrix

array([[ 4,  0,  0],
       [ 0,  8,  0],
       [ 0,  0, 12]])

### 6. Create a 3x3 matrix with random values


In [9]:
random_matrix = np.random.rand(3, 3)
random_matrix

array([[0.91552491, 0.93087625, 0.57216293],
       [0.00756754, 0.77647312, 0.94061362],
       [0.5865992 , 0.29553967, 0.8822094 ]])

### 7. Create a 3x3 matrix with normally distributed random values centered around 0


In [10]:
normal_matrix = np.random.randn(3, 3)
normal_matrix

array([[-0.91351748,  0.21644234,  0.0896773 ],
       [-0.20423322,  0.11968444,  1.37176909],
       [ 0.2278785 , -0.74539529,  0.84683695]])

### 8. Create a 4x4 matrix named mat and extract specified sections


In [13]:
mat = np.arange(0, 16).reshape(4, 4)
mat

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

##### 8.1 Extract the first row of the matrix


In [14]:
first_row = mat[0, :]
first_row

array([0, 1, 2, 3])

##### 8.2 Extract the third column of the matrix


In [15]:
third_column = mat[:, 2]
third_column

array([ 2,  6, 10, 14])

##### 8.3 Extract a 2x2 sub-matrix from the top-left corner


In [16]:
top_left_2x2 = mat[:2, :2]
top_left_2x2

array([[0, 1],
       [4, 5]])

# Pandas


#### 1. Reading the File and Displaying Basic Information

Question: <br/>
Load the dataset from yektanet.csv into a DataFrame named df. Then, use the info and describe methods to display basic information and statistical summaries. Explain what each output tells you about the dataset.


In [20]:
import pandas as pd

In [21]:
df = pd.read_csv('yektanet.csv')
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 219619 entries, 0 to 219618
Data columns (total 3 columns):
 #   Column       Non-Null Count   Dtype 
---  ------       --------------   ----- 
 0   keywords     219619 non-null  object
 1   segments     219619 non-null  object
 2   visit count  219619 non-null  int64 
dtypes: int64(1), object(2)
memory usage: 5.0+ MB


visit count
count  219619.000000
mean      498.717916
std       288.371056
min         0.000000
25%       250.000000
50%       498.000000
75%       748.000000
max       999.000000

#### Explanation: 
df.info() provides an overview of the dataset's structure, including column names, non-null counts and data types, which helps identify missing values or data types.<br/><br/>
df.describe() gives summary statistics for numerical columns, showing measures like mean, standard deviation, min, max, etc., which help understand data distribution.

#### 2. Accessing Data with iloc and loc

Question:<br/>

- Using iloc, select rows 10 to 20 and the first two columns.
- Using loc, display rows 15 to 25 and the columns keywords and visit count.


In [26]:
iloc_selection = df.iloc[10:21, :2]
iloc_selection

keywords  \
10               ['نتایج زنده', 'نتایج', 'زنده']   
11                       ['ریزش', 'تزریق', 'مو']   
12                      ['هنرمند', 'ببر', 'مرا']   
13                   ['لیگ برتر', 'برتر', 'لیگ']   
14                   ['اورجینال', 'علی', 'آهنگ']   
15            ['شام', 'لیست', 'متنوع', 'غذاهای']   
16               ['نتایج زنده', 'نتایج', 'زنده']   
17  ['سود', 'محاسبه', 'بانکی', 'آنلاین', 'بلند']   
18               ['نتایج زنده', 'نتایج', 'زنده']   
19                                       ['نوت']   
20               ['نتایج زنده', 'نتایج', 'زنده']   

                            segments  
10       ['maleSegment', 'varzeshi']  
11                 ['femaleSegment']  
12                   ['maleSegment']  
13  ['sarmayegozari', 'maleSegment']  
14                 ['femaleSegment']  
15                 ['femaleSegment']  
16                   ['maleSegment']  
17                   ['maleSegment']  
18                   ['maleSegment']  
19                   ['maleSegment']  
20                   ['maleSegment']

In [27]:
loc_selection = df.loc[15:25, ['keywords', 'visit count']]
loc_selection

keywords  visit count
15            ['شام', 'لیست', 'متنوع', 'غذاهای']          243
16               ['نتایج زنده', 'نتایج', 'زنده']          324
17  ['سود', 'محاسبه', 'بانکی', 'آنلاین', 'بلند']          810
18               ['نتایج زنده', 'نتایج', 'زنده']          436
19                                       ['نوت']          138
20               ['نتایج زنده', 'نتایج', 'زنده']          479
21                   ['پریود', 'ویدئو', 'تاثیر']          525
22                   ['انگلیسی', 'کوتاه', 'متن']          404
23                             ['رمان', 'انجمن']          809
24                                       ['رنگ']          900
25               ['نتایج زنده', 'نتایج', 'زنده']          607

#### 3. 3. Storing and Dropping the segments Column from the DataFrame

Question: <br/>
First, store the segments column in a variable named segments. Then, remove the segments column from the df DataFrame.


In [31]:
segments = df['segments']
df = df.drop(columns='segments')
df.head()

keywords  visit count
0                           ['باران', 'پروفایل']          127
1                ['نتایج زنده', 'نتایج', 'زنده']          822
2  ['معنی فارسی', 'معنی', 'فارسی', 'فارسی معنی']          726
3                ['نتایج زنده', 'نتایج', 'زنده']          307
4                ['نتایج زنده', 'نتایج', 'زنده']          778

#### 4. Creating Another DataFrame Using the segments Column and Concatenating It with the Main DataFrame

Question: <br/>
Use the segments column (which you previously stored in the segments variable) to create a new DataFrame called df_extra with columns keywords and segments. Then, concatenate df_extra with the main df DataFrame along the columns (axis=1).


In [35]:
df_extra = pd.DataFrame({'segments': segments})
df_combined = pd.concat([df, df_extra], axis=1)
df_combined.head()

keywords  visit count  \
0                           ['باران', 'پروفایل']          127   
1                ['نتایج زنده', 'نتایج', 'زنده']          822   
2  ['معنی فارسی', 'معنی', 'فارسی', 'فارسی معنی']          726   
3                ['نتایج زنده', 'نتایج', 'زنده']          307   
4                ['نتایج زنده', 'نتایج', 'زنده']          778   

                                            segments  
0  ['khanevadehvakhanedari', 'salamat', 'moosighi...  
1                                    ['maleSegment']  
2                                  ['femaleSegment']  
3                                    ['maleSegment']  
4                                    ['maleSegment']

#### 5. Filter the keywords that include more than 1400 websites:

Use groupby and the .filter() function to create a list of keywords that appear more than 1400 times in the DataFrame. Store the result in a variable called filtered_df.<br/>
Hint: First, use groupby for the keywords, then use len to check the count.


In [38]:
filtered_df = df_combined.groupby('keywords').filter(lambda x: len(x) > 1400)
filtered_df.head()

keywords  visit count                     segments
1   ['نتایج زنده', 'نتایج', 'زنده']          822              ['maleSegment']
3   ['نتایج زنده', 'نتایج', 'زنده']          307              ['maleSegment']
4   ['نتایج زنده', 'نتایج', 'زنده']          778              ['maleSegment']
10  ['نتایج زنده', 'نتایج', 'زنده']          418  ['maleSegment', 'varzeshi']
16  ['نتایج زنده', 'نتایج', 'زنده']          324              ['maleSegment']

#### 6. Add a popularity column to filtered_df:

Add a column called popularity to filtered_df, which represents the percentage of each website's visit count relative to the total visit count for that keyword.<br/>
Hint: After grouping by keywords, use the .transform() function on the visit count column to calculate the percentage of each website’s visit count relative to the total visit count of its keyword group, and then multiply by 100.


In [40]:
filtered_df['popularity'] = filtered_df.groupby('keywords')['visit count'].transform(lambda x: (x / x.sum()) * 100)
filtered_df.head()

keywords  visit count                     segments  \
1   ['نتایج زنده', 'نتایج', 'زنده']          822              ['maleSegment']   
3   ['نتایج زنده', 'نتایج', 'زنده']          307              ['maleSegment']   
4   ['نتایج زنده', 'نتایج', 'زنده']          778              ['maleSegment']   
10  ['نتایج زنده', 'نتایج', 'زنده']          418  ['maleSegment', 'varzeshi']   
16  ['نتایج زنده', 'نتایج', 'زنده']          324              ['maleSegment']   

    popularity  
1     0.016966  
3     0.006337  
4     0.016058  
10    0.008628  
16    0.006687